[tool.djlint]
indent = "2"
max_line_length = "79"
preserve_blank_lines = true
profile = "django"

[tool.isort]
profile = "black"
src_paths = "yatube"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "yatube.settings"
