# Generated by Django 2.2.16 on 2023-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'подписчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='posts/', verbose_name='картинка'
            ),
        ),
    ]
